import { chromium } from '/opt/codex/cua_node/lib/node_modules/playwright/index.mjs'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
const base = process.env.LIVINGTOWN_PREVIEW || 'http://127.0.0.1:4173'
const out = 'artifacts/family-dashboard'
const browser = await chromium.launch({ executablePath:'/usr/bin/chromium', headless:true, args:['--no-sandbox'] })
const results = []
async function until(check) { for(let i=0;i<400;i++){ if(await check()) return; await new Promise(r=>setTimeout(r,50)) }; throw Error('Expected UI state did not arrive') }
for(const width of [320,390,1440]) {
 const context = await browser.newContext({viewport:{width,height:900}})
 const page = await context.newPage(); const external=[]; const errors=[]
 await page.route('**/*', route => { const host = new URL(route.request().url()).hostname; if(!['127.0.0.1','localhost'].includes(host)){ external.push(route.request().url()); return route.abort() }; return route.continue() })
 page.on('pageerror',error=>errors.push(error.message))
 await page.goto(`${base}/?training=local`); await page.getByRole('heading',{name:'自分と家族の状況',exact:true}).waitFor()
 const home=page.locator('.family-dashboard')
 assert.equal(await home.getByRole('button',{name:'全員で行ける候補を計算する'}).isEnabled(),false)
 assert.equal(await page.locator('.maplibregl-canvas').count(),0)
 assert.equal(await page.locator('canvas').count(),0)
 await home.screenshot({path:`${out}/dashboard-${width}.png`})
 await home.getByRole('button',{name:'足・移動を編集',exact:false}).focus(); await page.keyboard.press('Enter')
 await until(async()=>await page.evaluate(()=>document.activeElement.id)==='family-editor-title')
 await home.locator('[data-preference=stairs]').getByRole('button',{name:'必要',exact:true}).click()
 await home.getByRole('button',{name:'編集を閉じて人物へ戻る'}).click()
 await until(async()=>await page.evaluate(()=>document.activeElement.dataset.part)==='legs')
 await home.getByRole('button',{name:'未入力をスキップしてこの人を確認'}).click()
 await home.getByRole('button',{name:'家族を追加する（本人を含め最大8人）'}).click()
 await home.getByRole('button',{name:'腕・持つ／支えてもらうを編集',exact:false}).click()
 await home.locator('[data-preference=baggage]').getByRole('button',{name:'できれば希望',exact:true}).click()
 await home.getByRole('button',{name:'編集を閉じて人物へ戻る'}).click()
 await home.getByRole('button',{name:'頭周り・案内の受け取り方を編集',exact:false}).click()
 await home.locator('[data-preference=explanation]').getByRole('button',{name:'わからない',exact:true}).click()
 await home.getByRole('button',{name:'編集を閉じて人物へ戻る'}).click()
 await home.getByRole('button',{name:'足・移動を編集',exact:false}).click()
 await home.locator('[data-preference=rest]').getByRole('button',{name:'必要',exact:true}).click()
 await home.getByRole('button',{name:'編集を閉じて人物へ戻る'}).click()
 await home.getByRole('button',{name:'未入力をスキップしてこの人を確認'}).click()
 await home.getByRole('button',{name:'家族1（架空）を外す',exact:true}).click()
 await home.locator('.family-removed-members summary').click()
 await home.getByRole('button',{name:'家族1（架空）を元に戻す',exact:true}).click()
 assert.match(await home.locator('[data-part=arms]').innerText(),/荷物を運ぶ助けがほしい：できれば希望/)
 await home.locator('.family-conditions input').check()
 await home.getByRole('button',{name:'全員で行ける候補を計算する'}).click()
 await home.getByRole('heading',{name:'家族全員の候補と理由',exact:true}).waitFor()
 await until(async()=>await page.evaluate(()=>document.activeElement.id)==='family-results-title')
 const south = home.locator('[data-route=hill-rest]')
 assert.match(await south.innerText(),/条件上の候補/)
 await south.getByText('全員の配慮とこの道の根拠を見る',{exact:true}).click()
 assert.match(await south.innerText(),/家族1（架空）/)
 assert.match(await south.innerText(),/200m以内/)
 await home.locator('.family-results > .family-check input').check()
 await south.getByRole('button',{name:'この道を訓練の案内に採用する'}).click()
 await home.locator('.family-active').waitFor()
 await home.locator('.family-active').screenshot({path:`${out}/adopted-${width}.png`})
 await home.getByRole('button',{name:'南側の未確認投稿',exact:true}).click()
 await until(async()=>/未確認・要確認/.test(await south.innerText()))
 assert.match(await home.locator('.family-active').innerText(),/最新情報では未確認/)
 assert.equal(await south.getByRole('button',{name:'この道を訓練の案内に採用する'}).isEnabled(),false)
 await home.getByRole('button',{name:'南側の通行不可・追認あり',exact:true}).click()
 await until(async()=>/全員の必要条件を満たす候補はありません/.test(await home.innerText()))
 assert.match(await home.locator('.family-active').innerText(),/南側の休憩地点/)
 await home.getByRole('button',{name:'南側は通れるという矛盾投稿',exact:true}).click()
 await home.getByText('受信した投稿の分類・根拠・更新日時',{exact:true}).click()
 assert.match(await home.locator('.family-events').innerText(),/矛盾・要確認/)
 await home.locator('.family-results').screenshot({path:`${out}/no-candidate-${width}.png`})
 await home.locator('.family-events').screenshot({path:`${out}/event-reasons-${width}.png`})
 await home.getByRole('button',{name:'南側の投稿を撤回',exact:true}).click()
 assert.match(await south.innerText(),/30秒の再開保留/)
 await home.getByRole('button',{name:'古い南側投稿を受信',exact:true}).click()
 assert.match(await home.locator('.family-timeline').innerText(),/古い版/)
 await home.getByRole('button',{name:'架空の時点を31秒進める'}).click()
 await until(async()=>/条件上の候補/.test(await south.innerText()))
 assert.match(await home.locator('.family-active').innerText(),/最新情報では未確認/)
 await home.getByRole('button',{name:'南側投稿を重複受信',exact:true}).click()
 assert.match(await home.locator('.family-timeline').innerText(),/重複/)
 await home.getByRole('button',{name:'南北の投稿を同時受信',exact:true}).click()
 assert.match(await home.innerText(),/全員の必要条件を満たす候補はありません/)
 const overflow = await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)
 assert.equal(overflow,false)
 if(width===1440) {
  await page.locator('.my-reports-link').click()
  assert.equal(await page.locator('.beginner-home').count(),1)
  assert.equal(await page.locator('.family-dashboard').count(),1)
 }
 assert.deepEqual(errors,[]); assert.deepEqual(external,[])
 results.push({width,passed:true,externalRequests:external.length,pageErrors:errors,overflow,checks:['body-part editing','member isolation','remove/undo','family intersection','source/date','confirmation','no-candidate','pending warning','old/duplicate/simultaneous','contradiction','withdraw/hold','no automatic active switch','focus','no map on entry']})
 await context.close()
}
// Four- and eight-person households, with a compact switcher on each width.
for(const width of [320,390,1440]) {
 const context=await browser.newContext({viewport:{width,height:900}}); const page=await context.newPage(); const external=[]; const errors=[]; const modelRequests=[]
 await page.route('**/*',route=>{ const url=new URL(route.request().url()); if(!['127.0.0.1','localhost'].includes(url.hostname)){ external.push(url.href);return route.abort() }; if(url.pathname.endsWith('.glb')) modelRequests.push(url.pathname); return route.continue() })
 page.on('pageerror',error=>errors.push(error.message))
 await page.goto(`${base}/?training=local`)
 const home=page.locator('.family-dashboard')
 const add=home.getByRole('button',{name:'家族を追加する（本人を含め最大8人）',exact:true})
 const confirmPerson=home.getByRole('button',{name:'未入力をスキップしてこの人を確認',exact:true})
 await home.getByRole('button',{name:'足・移動を編集',exact:false}).click()
 await home.locator('[data-preference=stairs]').getByRole('button',{name:'必要',exact:true}).click()
 await home.getByRole('button',{name:'編集を閉じて人物へ戻る'}).click(); await confirmPerson.click()
 for(let number=1; number<=7; number++) {
  await add.click()
  assert.equal(await home.locator('.family-current-member .family-member').count(),1)
  assert.match(await home.locator('#selected-person-title').innerText(),new RegExp(`家族${number}`))
  assert.equal(await home.locator('.family-other-members').getAttribute('open'),null)
  if(number===1) {
   await home.getByRole('button',{name:'足・移動を編集',exact:false}).click()
   await home.locator('[data-preference=rest]').getByRole('button',{name:'必要',exact:true}).click()
   await home.getByRole('button',{name:'編集を閉じて人物へ戻る'}).click()
  }
  if(number===7) {
   await home.getByRole('button',{name:'腕・持つ／支えてもらうを編集',exact:false}).click()
   await home.locator('[data-preference=baggage]').getByRole('button',{name:'できれば希望',exact:true}).click()
   await home.getByRole('button',{name:'編集を閉じて人物へ戻る'}).click()
  }
  await confirmPerson.click()
  if(number===3) {
   assert.match(await home.locator('.family-count').innerText(),/本人を含む4人／最大8人/)
   await home.locator('.family-conditions input').check(); await home.getByRole('button',{name:'全員で行ける候補を計算する'}).click()
   await home.locator('[aria-labelledby=family-members-title]').screenshot({path:`${out}/four-people-${width}.png`})
   assert.match(await home.locator('[data-route=hill-rest]').innerText(),/条件上の候補/)
  }
 }
 assert.match(await home.locator('.family-count').innerText(),/本人を含む8人／最大8人/)
 assert.equal(await add.isEnabled(),false)
 await home.locator('[aria-labelledby=family-members-title]').screenshot({path:`${out}/eight-people-count-${width}.png`})
 await home.locator('.family-other-members summary').click()
 assert.equal(await home.locator('.family-other-members .family-member').count(),7)
 await home.locator('.family-other-members').screenshot({path:`${out}/eight-people-list-${width}.png`})
 await home.locator('.family-other-members .family-member').getByRole('button',{name:'本人（架空）',exact:false}).click()
 await until(async()=>/本人/.test(await home.locator('#selected-person-title').innerText()))
 assert.match(await home.locator('[data-part=legs]').innerText(),/階段を避けたい：必要/)
 assert.match(await home.locator('[data-part=arms]').innerText(),/荷物を運ぶ助けがほしい：スキップ/)
 await home.locator('.family-other-members summary').click()
 await home.locator('.family-other-members .family-member').getByRole('button',{name:'家族7（架空）',exact:false}).first().click()
 assert.match(await home.locator('[data-part=arms]').innerText(),/荷物を運ぶ助けがほしい：できれば希望/)
 await home.locator('.family-conditions input').check(); await home.getByRole('button',{name:'全員で行ける候補を計算する'}).click()
 const south=home.locator('[data-route=hill-rest]')
 await south.getByText('全員の配慮とこの道の根拠を見る',{exact:true}).click()
 assert.equal(await south.getByRole('heading',{level:5}).count(),8)
 assert.match(await south.innerText(),/家族7（架空）：荷物を運ぶ助けがほしい/)
 await south.getByText('全員の配慮とこの道の根拠を見る',{exact:true}).click()
 await home.locator('.family-person').screenshot({path:`${out}/eight-people-selected-${width}.png`})
 await home.getByRole('button',{name:'家族7（架空）を外す',exact:true}).click()
 assert.equal(await add.isEnabled(),true)
 await add.click(); assert.match(await home.locator('#selected-person-title').innerText(),/家族8/)
 assert.match(await home.locator('[data-part=arms]').innerText(),/荷物を運ぶ助けがほしい：未入力/)
 await home.locator('.family-removed-members summary').click()
 const restore=home.getByRole('button',{name:'家族7（架空）を元に戻す',exact:true})
 assert.equal(await restore.isEnabled(),false)
 await home.getByRole('button',{name:'家族8（架空）を外す',exact:true}).click()
 assert.equal(await restore.isEnabled(),true)
 await restore.click()
 assert.match(await home.locator('#selected-person-title').innerText(),/家族7/)
 assert.match(await home.locator('[data-part=arms]').innerText(),/荷物を運ぶ助けがほしい：できれば希望/)
 assert.match(await home.locator('.family-count').innerText(),/本人を含む8人/)
 assert.equal(await page.locator('canvas').count(),0); assert.deepEqual(modelRequests,[])
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)
 assert.equal(overflow,false); assert.deepEqual(errors,[]); assert.deepEqual(external,[])
 results.push({width,people:8,passed:true,externalRequests:0,pageErrors:errors,overflow,modelRequests:0,checks:['4/8 total including self','individual edits and reasons','compact member switcher','delete then fresh add','restore capacity','fresh identity','no persistent 3D for other people']})
 await context.close()
}
for(const failure of [false,true]) {
 const context=await browser.newContext({viewport:{width:390,height:900}}); const page=await context.newPage(); const external=[]
 await page.route('**/*',route=>{const url=new URL(route.request().url()); if(!['127.0.0.1','localhost'].includes(url.hostname)){external.push(url.href);return route.abort()} if(failure && url.pathname.endsWith('.glb')) return route.abort(); return route.continue()})
 await page.goto(`${base}/?training=local`)
 const home=page.locator('.family-dashboard')
 await home.getByRole('button',{name:'人物を3Dで見る（任意）',exact:true}).click()
 await until(async()=>failure ? /人物の3Dを利用できません/.test(await home.innerText()) : await home.locator('.beginner-guide-canvas canvas').count()>0 && await home.locator('.beginner-guide-canvas').isVisible())
 if(!failure) { const box=await home.locator('.beginner-guide-canvas canvas').boundingBox(); assert.ok(Math.abs(box.width-box.height)<1,'3D canvas retains its square aspect ratio') }
 await home.locator('.family-person').screenshot({path:`${out}/guide-${failure?'failed':'ready'}-390.png`})
 await home.getByRole('button',{name:'足・移動を編集',exact:false}).click(); assert.equal(await home.locator('.family-editor').isVisible(),true)
 await home.getByRole('button',{name:'編集を閉じて人物へ戻る'}).click()
 await home.getByRole('button',{name:'家族を追加する（本人を含め最大8人）'}).click()
 assert.equal(await home.locator('canvas').count(),0)
 assert.deepEqual(external,[])
 results.push({guide:failure?'failure':'normal',passed:true,externalRequests:0,memberSwitchDisposesCanvas:true})
 await context.close()
}
await browser.close()
await fs.writeFile(`${out}/browser-results.json`,JSON.stringify({base,results},null,2)+'\n')
console.log(JSON.stringify(results,null,2))
