import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {sceneFixture} from './scene-fixture.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});
const checks=[];
try {
 for(const [name,width,height] of [['desktop',1440,1000],['iphone',390,844]]){
  const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
  await page.route('**/src/map3d/NavaraScene.ts*',r=>r.fulfill({contentType:'application/javascript',body:sceneFixture}));
  await page.goto('http://127.0.0.1:4173/?training=local&view=3d&mode=advanced&lang=ja');
  const surface=page.locator('.map-surface--3d');await surface.waitFor();
  const settings=page.locator('.navara-settings');const summary=settings.locator(':scope > summary');
  await summary.waitFor();assert.equal(await settings.getAttribute('open'),null);
  assert.equal(await page.locator('.navara-diagnostics-grid').isVisible(),false);
  const frame=await page.locator('.navara-map-frame').boundingBox();const dock=await page.locator('.navara-controls').boundingBox();assert.ok(dock.y>=frame.y+frame.height-1);
  assert.equal(await page.locator('.navara-simulation-note').isVisible(),true);
  assert.equal(await page.locator('.navara-attribution').isVisible(),true);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await surface.screenshot({path:`artifacts/3d-readability/after-${name}.png`});
  await summary.focus();await page.keyboard.press('Enter');assert.notEqual(await settings.getAttribute('open'),null);
  const weather=settings.locator('select').nth(0);await weather.selectOption('rain');assert.equal(await weather.inputValue(),'rain');
  const diagnostic=page.locator('.navara-diagnostics');await diagnostic.locator('summary').click();await page.locator('.navara-diagnostics-grid').waitFor();
  await page.keyboard.press('Escape');assert.equal(await diagnostic.getAttribute('open'),null);assert.notEqual(await settings.getAttribute('open'),null);
  assert.equal(await diagnostic.locator('summary').evaluate(e=>document.activeElement===e),true);
  await page.keyboard.press('Escape');assert.equal(await settings.getAttribute('open'),null);assert.equal(await summary.evaluate(e=>document.activeElement===e),true);
  await summary.evaluate(e=>{e.click();e.click()});assert.equal(await settings.getAttribute('open'),null);
  await summary.click();await settings.locator('select').nth(1).selectOption('low');
  await diagnostic.locator('summary').click();
  await surface.screenshot({path:`artifacts/3d-readability/settings-${name}.png`});
  await settings.getByRole('button',{name:'設定を閉じる',exact:true}).click();assert.equal(await settings.getAttribute('open'),null);
  await page.getByRole('button',{name:'地図を大きく見る',exact:true}).click();
  await summary.click();await settings.getByRole('button',{name:'設定を閉じる',exact:true}).scrollIntoViewIfNeeded();
  await settings.locator('select').first().focus();await page.keyboard.press('Escape');
  assert.equal(await page.locator('[data-map-focus="active"]').count(),1);
  await page.getByRole('button',{name:'地図を戻す',exact:true}).click();
  await page.getByRole('button',{name:'地図だけ見る',exact:true}).click();assert.equal(await page.locator('.navara-controls').isVisible(),false);assert.equal(await page.locator('.navara-attribution').isVisible(),true);
  await page.keyboard.press('Escape');assert.equal(await page.locator('.navara-controls').isVisible(),true);
  await page.locator('.navara-map-overlay').getByRole('button',{name:'2Dに戻る',exact:true}).click();await page.locator('.town-map').waitFor();
  await page.getByRole('button',{name:'3Dで見る',exact:true}).click();await summary.waitFor();assert.equal(await settings.getAttribute('open'),null);
  await page.goto('http://127.0.0.1:4173/?training=local&view=3d&mode=simple&lang=ja');
  await summary.waitFor();await page.getByRole('button',{name:'家族の訓練を始める →',exact:true}).click();
  await page.route('**/api/training/questions',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({provider:'fake',fields:['household_id','scenario','weather','time_of_day']})}));
  const assistant=page.locator('.training-assistant');await assistant.getByRole('button',{name:'条件の質問を開始',exact:true}).click();
  for(const [i,value] of ['h-wheelchair','flood','rain','day'].entries()) await assistant.locator('select').nth(i).selectOption(value);
  await assistant.getByRole('checkbox').check();await assistant.getByRole('button',{name:'確認した条件で経路を比較'}).click();
  await assistant.getByRole('button',{name:'この家族の3D訓練へ'}).click();
  await page.getByRole('button',{name:'3Dで避難ルートを確認',exact:true}).click();
  const walk=page.locator('.navara-walkthrough-controls');await walk.waitFor();
  const walkBox=await walk.boundingBox();const mapBox=await page.locator('.navara-map-frame').boundingBox();assert.ok(walkBox.y>=mapBox.y+mapBox.height-1);
  await walk.getByRole('button',{name:'次へ',exact:true}).click();
  await summary.click();await settings.locator('select').first().focus();await page.keyboard.press('Escape');
  assert.equal(await page.locator('[data-walkthrough="active"]').count(),1);
  await surface.screenshot({path:`artifacts/3d-readability/walkthrough-${name}.png`});
  await page.keyboard.press('Escape');assert.equal(await page.locator('[data-walkthrough="active"]').count(),0);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.deepEqual(errors,[]);checks.push(`${name}: no map/control overlap, collapsed diagnostics, settings weather/quality, keyboard/Escape/focus, double toggle, focus scrolling, map-only attribution, 2D/back/revisit, simple training walkthrough/next/Escape`);
  await page.close();
 }
 await writeFile('artifacts/3d-readability/verification.json',JSON.stringify({renderer:'test fixture; external 3D assets unverified',checks,pageErrors:[]},null,2)+'\n');console.log(JSON.stringify({checks,pageErrors:[]},null,2));
} finally {await browser.close();}
